apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sqlserver-storage
  resources:
    requests:
      storage: 5Gi
