apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-service
  template:
    metadata:
      labels:
        app: weather-service
    spec:
      restartPolicy: Always
      containers:
        - name: weather-service
          image: natimershon/weather_service:latest  
          ports:
            - containerPort: 5000  
          env:
              - name: MSSQL_HOST
                value: "sqlserver.default.svc.cluster.local"  
              - name: MSSQL_PORT
                value: "1433"
              - name: MSSQL_USER
                value: "sa"
              - name: MSSQL_DATABASE
                value: "WeatherDB"
              - name: SA_PASSWORD
                value: "YourPassword123"
              - name: FLASK_PORT
                value: "5000"
          resources: 
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe: 
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:  
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 5
